### **Read the file and check heads**

In [ ]:
import numpy as np
import pandas as pd

from google.colab import drive
drive.mount('/content/gdrive')

df = pd.read_csv('/content/gdrive/My Drive/Colab_Notebooks/Class 11 (04 June 2021) - Data Analysis/dataset.csv')

#Check all the column and row names
df.head()

### **Check number of rows and columns**

In [ ]:
#check shape of the dataset
df.shape

(3333, 21)

In [ ]:
#or, 
x, y = df.shape #x is the row and y is the column
print("Total rows are:",x)
print("Total columns are:",y)

Total rows are: 3333
Total columns are: 21

### **Check Columns Name**

In [ ]:
df.columns

Index(['state', 'account length', 'area code', 'phone number',
       'international plan', 'voice mail plan', 'number vmail messages',
       'total day minutes', 'total day calls', 'total day charge',
       'total eve minutes', 'total eve calls', 'total eve charge',
       'total night minutes', 'total night calls', 'total night charge',
       'total intl minutes', 'total intl calls', 'total intl charge',
       'customer service calls', 'churn'],
      dtype='object')

### **Check Data Types**

In [ ]:
df.dtypes

state                      object
account length              int64
area code                   int64
phone number               object
international plan         object
voice mail plan            object
number vmail messages       int64
total day minutes         float64
total day calls             int64
total day charge          float64
total eve minutes         float64
total eve calls             int64
total eve charge          float64
total night minutes       float64
total night calls           int64
total night charge        float64
total intl minutes        float64
total intl calls            int64
total intl charge         float64
customer service calls      int64
churn                        bool
dtype: object

### **Check Whole info about the dataset**

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3333 entries, 0 to 3332
Data columns (total 21 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   state                   3333 non-null   object
 1   account length          3333 non-null   int64
 2   area code               3333 non-null   int64
 3   phone number            3333 non-null   object
 4   international plan      3333 non-null   object
 5   voice mail plan         3333 non-null   object
 6   number vmail messages   3333 non-null   int64
 7   total day minutes       3333 non-null   float64
 8   total day calls         3333 non-null   int64
 9   total day charge        3333 non-null   float64
 10  total eve minutes       3333 non-null   float64
 11  total eve calls         3333 non-null   int64
 12  total eve charge        3333 non-null   float64
 13  total night minutes     3333 non-null   float64
 14  total night calls       3333 non-null   int64
 15  total night charge      3333 non-null   float64
 16  total intl minutes      3333 non-null   float64
 17  total intl calls        3333 non-null   int64
 18  total intl charge       3333 non-null   float64
 19  customer service calls  3333 non-null   int64
 20  churn                   3333 non-null   bool
dtypes: bool(1), float64(8), int64(8), object(4)
memory usage: 524.2+ KB

### **Want to change the data type of a column?**
For example, churn has the data type, which is bool. change it to int.

In [ ]:
df['churn'] = df['churn'].astype(int)
df['churn'].dtypes

dtype('int64')

### **Describe the dataset**
The describe() method is used for calculating some statistical data like percentile, mean, std and so on of the numerical values of the Series or DataFrame. It analyzes both numeric and object series and also the DataFrame column sets of mixed data types.

In [ ]:
df.describe()

       account length    area code  ...  customer service calls        churn
count     3333.000000  3333.000000  ...             3333.000000  3333.000000
mean       101.064806   437.182418  ...                1.562856     0.144914
std         39.822106    42.371290  ...                1.315491     0.352067
min          1.000000   408.000000  ...                0.000000     0.000000
25%         74.000000   408.000000  ...                1.000000     0.000000
50%        101.000000   415.000000  ...                1.000000     0.000000
75%        127.000000   510.000000  ...                2.000000     0.000000
max        243.000000   510.000000  ...                9.000000     1.000000

[8 rows x 17 columns]

# **Count the values for a specific column**
normalize = True will give the result with percentage.

In [ ]:
counts = df['voice mail plan'].value_counts()
print(counts,"\n")

counts = df['voice mail plan'].value_counts(normalize = True)
print(counts)

no     2411
yes     922
Name: voice mail plan, dtype: int64

no     0.723372
yes    0.276628
Name: voice mail plan, dtype: float64

### **Sort values in accending or decending order for a column**

In [ ]:
df.sort_values(by=['account length'], ascending=[True])

     state  account length  ...  customer service calls churn
923     MS               1  ...                       1     0
1838    IA               1  ...                       1     0
1490    TN               1  ...                       1     0
2960    TX               1  ...                       5     1
2423    SC               1  ...                       0     0
...    ...             ...  ...                     ...   ...
1886    ID             224  ...                       3     0
1751    WY             225  ...                       1     0
1551    MI             225  ...                       0     1
1408    NM             232  ...                       1     0
817     UT             243  ...                       2     0

[3333 rows x 21 columns]

### **To find the max value for every column**

In [ ]:
df.apply(np.max)

state                           WY
account length                 243
area code                      510
phone number              422-9964
international plan             yes
voice mail plan                yes
number vmail messages           51
total day minutes            350.8
total day calls                165
total day charge             59.64
total eve minutes            363.7
total eve calls                170
total eve charge             30.91
total night minutes            395
total night calls              175
total night charge           17.77
total intl minutes              20
total intl calls                20
total intl charge              5.4
customer service calls           9
churn                            1
dtype: object

### **To find the max value for a specific column**

In [ ]:
df['account length'].max()

243

### **For replacing values with another value**
0 -> 2
1 -> 3

In [ ]:
df['international plan'] = df['international plan'].replace('no', 0)
df['international plan'] = df['international plan'].replace('yes', 1)
df['international plan'].value_counts()

0    3010
1     323
Name: international plan, dtype: int64

### **QUES: How much time (on average) do churned users spend on the phone during daytime?**

In [1]:
# for i in df['churn']:
#   if i == True:
#     print(df['total day minutes'].mean())

avgTime= df[df['churn'] == True]['total day minutes'].mean()
print("Avg time is: ", avgTime)

NameError: ignored

### **QUES: What is the maximum length of international calls among loyal users (Churn == 0) who do not have an international plan?**

In [ ]:
maxLength = df[(df['churn'] == False) & (df['international plan'] == 'no')]['total intl minutes'].max()
print("maximum length is:",maxLength)

maximum length is: 18.9

In [ ]:
# if (df['churn'] == 0 and df['international plan'] == 'no'):
#   print(df['total intl minutes'].max())

ValueError: ignored